# 適用する前に tenant-workshopXX を自分の namespace に置き換えてください。
# すべてのファイルをまとめて置き換える方が簡単です: README の番号の置換に関するセクションを参照してください。
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Bucket
metadata:
  name: my-images
  namespace: tenant-workshopXX
spec:
  users:
    app: {}
