# 적용하기 전에 tenant-workshopXX를 자신의 namespace로 교체하세요.
# 모든 파일에서 한 번에 처리하는 것이 더 쉽습니다: README의 번호 치환 관련 섹션을 참고하세요.
#
apiVersion: apps.cozystack.io/v1alpha1
kind: VMDisk
metadata:
  name: convert-tools
  namespace: tenant-workshopXX
spec:
  source:
    image:
      name: ubuntu-20.04
  storage: 25Gi
  storageClass: replicated
---
apiVersion: apps.cozystack.io/v1alpha1
kind: VMInstance
metadata:
  name: convert
  namespace: tenant-workshopXX
spec:
  instanceType: u1.large
  instanceProfile: ubuntu
  runStrategy: Always
  disks:
    - name: convert-tools
  cloudInit: |
    #cloud-config
    password: ubuntu
    chpasswd: { expire: false }
    ssh_pwauth: true
    package_update: true
    packages: [ libguestfs-tools, virt-v2v, qemu-utils ]
    runcmd:
      - [ bash, -c, "wget -q -O /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x /usr/local/bin/mc" ]