# 적용하기 전에 tenant-workshopXX를 자신의 namespace로 바꾸세요.
# 모든 파일에서 한 번에 바꾸는 것이 더 쉽습니다: 번호 치환에 관한 README 섹션을 참고하세요.
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Postgres
metadata:
  name: db
  namespace: tenant-workshopXX
spec:
  replicas: 1
  size: 10Gi
  storageClass: local
  resourcesPreset: t1.micro
  users:
    orders:
      password: Orders2019!
  databases:
    orders:
      roles:
        admin: [ orders ]
---
apiVersion: apps.cozystack.io/v1alpha1
kind: Kafka
metadata:
  name: kafka
  namespace: tenant-workshopXX
spec:
  kafka:
    replicas: 1
    size: 10Gi
    storageClass: local
    resourcesPreset: c1.small
  zookeeper:
    replicas: 1
    size: 5Gi
    storageClass: local
    resourcesPreset: c1.small
  topics:
    - name: orders
      partitions: 1
      replicas: 1
      config: {}