# 应用前，请将 tenant-workshopXX 替换为你自己的 namespace。
# 一次性替换所有文件更方便：参见 README 中关于替换编号的章节。
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Bucket
metadata:
  name: my-images
  namespace: tenant-workshopXX
spec:
  users:
    app: {}
