# लागू करने से पहले tenant-workshopXX को अपने namespace से बदलें।
# सभी फ़ाइलों में एक साथ करना आसान है: README देखें, नंबर प्रतिस्थापन वाला अनुभाग।
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Bucket
metadata:
  name: my-images
  namespace: tenant-workshopXX
spec:
  users:
    app: {}
