# Ersetzen Sie vor dem Anwenden tenant-workshopXX durch Ihren eigenen Namespace.
# Einfacher auf einmal über alle Dateien: siehe README, Abschnitt zum Ersetzen der Nummer.
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Bucket
metadata:
  name: my-images
  namespace: tenant-workshopXX
spec:
  users:
    app: {}