# 应用前，请将 tenant-workshopXX 替换为你自己的 namespace。
# 更简单的做法是一次性替换所有文件：参见 README 中关于替换编号的章节。
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Postgres
metadata:
  name: db
  namespace: tenant-workshopXX
spec:
  replicas: 1
  size: 10Gi
  storageClass: local
  resourcesPreset: t1.micro
  users:
    orders:
      password: Orders2019!
  databases:
    orders:
      roles:
        admin: [ orders ]
---
apiVersion: apps.cozystack.io/v1alpha1
kind: Kafka
metadata:
  name: kafka
  namespace: tenant-workshopXX
spec:
  kafka:
    replicas: 1
    size: 10Gi
    storageClass: local
    resourcesPreset: c1.small
  zookeeper:
    replicas: 1
    size: 5Gi
    storageClass: local
    resourcesPreset: c1.small
  topics:
    - name: orders
      partitions: 1
      replicas: 1
      config: {}