# 적용하기 전에 tenant-workshopXX를 자신의 namespace로 바꾸세요.
# 모든 파일에서 한 번에 바꾸는 것이 더 쉽습니다: README의 번호 치환에 관한 섹션을 참고하세요.
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Bucket
metadata:
  name: my-images
  namespace: tenant-workshopXX
spec:
  users:
    app: {}
