# 適用する前に、tenant-workshopXX を自分の namespace に置き換えてください。
# すべてのファイルを一度に置き換えるほうが簡単です: README の番号の置換に関するセクションを参照してください。
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Bucket
metadata:
  name: my-images
  namespace: tenant-workshopXX
spec:
  users:
    app: {}