# 適用する前に、tenant-workshopXX を自分の namespace に置き換えてください。
# 全ファイルまとめて行う方が簡単です: README の番号の置換に関するセクションを参照してください。
#
apiVersion: apps.cozystack.io/v1alpha1
kind: Postgres
metadata:
  name: db
  namespace: tenant-workshopXX
spec:
  replicas: 1
  size: 10Gi
  storageClass: local
  resourcesPreset: t1.micro
  users:
    orders:
      password: Orders2019!
  databases:
    orders:
      roles:
        admin: [ orders ]
---
apiVersion: apps.cozystack.io/v1alpha1
kind: Kafka
metadata:
  name: kafka
  namespace: tenant-workshopXX
spec:
  kafka:
    replicas: 1
    size: 10Gi
    storageClass: local
    resourcesPreset: c1.small
  zookeeper:
    replicas: 1
    size: 5Gi
    storageClass: local
    resourcesPreset: c1.small
  topics:
    - name: orders
      partitions: 1
      replicas: 1
      config: {}
